version: '2.1'

services:
  authDb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'

  testDb:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: testPassword
    ports:
      - 5433:5432

  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379

  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017

  adminer:
    image: adminer
    ports:
      - 9000:8080

  testRedis:
    image: redis:6.2.6
    ports:
      - 6380:6379
  rabbitmq:
    image: rabbitmq:3.9.14
    ports:
      - 5672:5672
