import { serverInit } from '../../../../server'

import { knex, prepareDbForTests, sqlClose, sqlInit } from '../../../../databases/sql'
import { expectationFailed } from '@hapi/boom'

describe('Happy Path get action statuses endpoint test with DB connection', () => {
  const actionTableName = 'action'

  const testUrl = '/api/actions/getactionstatuses'
  const testMethod = 'POST'

  let server

  beforeAll(async () => {
    await sqlInit()
    server = await serverInit()
    await prepareDbForTests()
  })

  beforeEach(async () => {
    await prepareDbForTests()
  })

  afterAll(async () => {
    await knex(actionTableName).truncate()

    await server.stop()
    await sqlClose()
  })

  describe('Happy Path', () => {
    test('should return 200 and an object of the all action statuses (In this case by the child some actions done sofar)', async () => {
      const injectOptions = {
        method: testMethod,
        url: testUrl,
        payload: { accountId: 1, childId: 1 },
      }

      //The timeStamps are generated by the date.now so the test doesn't check the exact value
      const expectedResponse = [
        { id: 1, actionId: 1, actionStart: 1656249486, actionEnd: null, actionName: 'Sleep', isRecording: true },
        {
          id: 2,
          actionId: 2,
          actionStart: 1656248786,
          actionEnd: 1656248986,
          actionName: 'BrestFeed',
          isRecording: false,
        },
        { id: 3, actionId: 3, actionStart: 1656249086, actionEnd: 1656249386, actionName: 'Walk', isRecording: false },
        { id: null, actionId: 4, actionStart: null, actionEnd: null, isRecording: false, actionName: 'Falling asleep' },
        { id: null, actionId: 5, actionStart: null, actionEnd: null, isRecording: false, actionName: 'Eat' },
      ]

      const res = await server.inject(injectOptions)

      const responseBody = JSON.parse(res.payload)

      expect(responseBody.length).toBe(5)
      expect(res.statusCode).toEqual(200)
      expect(responseBody[0].id).toBeTruthy()
      expect(responseBody[0].actionId).toBeTruthy()
      expect(responseBody[0].actionEnd).toBeFalsy()
      expect(responseBody[0].actionName).toEqual('Sleep')
      expect(responseBody[0].isRecording).toBeTruthy()

      expect(res.statusCode).toEqual(200)
      expect(responseBody[1].id).toBeTruthy()
      expect(responseBody[1].actionId).toBeTruthy()
      expect(responseBody[1].actionEnd).toBeTruthy()
      expect(responseBody[1].actionName).toEqual('BrestFeed')
      expect(responseBody[1].isRecording).toBeFalsy()

      expect(res.statusCode).toEqual(200)
      expect(responseBody[2].id).toBeTruthy()
      expect(responseBody[2].actionId).toBeTruthy()
      expect(responseBody[2].actionEnd).toBeTruthy()
      expect(responseBody[2].actionName).toEqual('Walk')
      expect(responseBody[2].isRecording).toBeFalsy()

      expect(res.statusCode).toEqual(200)
      expect(responseBody[3].id).toBeFalsy()
      expect(responseBody[3].actionId).toBeTruthy()
      expect(responseBody[3].actionEnd).toBeFalsy()
      expect(responseBody[3].actionName).toEqual('Falling asleep')
      expect(responseBody[3].isRecording).toBeFalsy()

      expect(res.statusCode).toEqual(200)
      expect(responseBody[4].id).toBeFalsy()
      expect(responseBody[4].actionId).toBeTruthy()
      expect(responseBody[4].actionEnd).toBeFalsy()
      expect(responseBody[4].actionName).toEqual('Eat')
      expect(responseBody[4].isRecording).toBeFalsy()
    })

    test('should return 200 and an object of the all action statuses (In this case by the child no any actions have been recorded so all the start and end should be null)', async () => {
      const injectOptions = {
        method: testMethod,
        url: testUrl,
        payload: { accountId: 1, childId: 3 },
      }

      //The timeStamps are generated by the date.now so the test doesn't check the exact value
      const expectedResponse = [
        { id: null, actionId: 1, actionStart: null, actionEnd: null, isRecording: false, actionName: 'Sleep' },
        { id: null, actionId: 2, actionStart: null, actionEnd: null, isRecording: false, actionName: 'BrestFeed' },
        { id: null, actionId: 3, actionStart: null, actionEnd: null, isRecording: false, actionName: 'Walk' },
        { id: null, actionId: 4, actionStart: null, actionEnd: null, isRecording: false, actionName: 'Falling asleep' },
        { id: null, actionId: 5, actionStart: null, actionEnd: null, isRecording: false, actionName: 'Eat' },
      ]

      const res = await server.inject(injectOptions)

      const responseBody = JSON.parse(res.payload)

      //check the actionIds enums
      expect(res.statusCode).toEqual(200)

      expect(responseBody).toEqual(expectedResponse)
    })
  })
})
